config/routes.rb
Rails.application.routes.draw do

  root 'examinations#index'

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  
  get 'exam' => 'examinations#index'
  get 'exam/add' => 'examinations#add'
  post 'exam/add' => 'examinations#create'
  delete 'exam/:id/delete' => 'examinations#destroy', as: :delete_examination
  get 'exam/:id' => 'examinations#show', as: :show_examination
  post 'exam/submit' => 'examinations#submit'
  
  get 'questions' => 'questions#index'
  get 'questions/add' => 'questions#add'
  get 'questions/:id' => 'questions#show', as: :question
  get 'questions/:id/edit' => 'questions#edit', as: :edit_question
  post 'questions' => 'questions#save'
  patch 'questions/:id' => 'questions#update'

end

app/models/exam_log.rb
class ExamLog < ActiveRecord::Base
end

app/models/examination.rb
class Examination < ActiveRecord::Base
	has_many :questions
end

app/models/question.rb
class Question < ActiveRecord::Base
	belongs_to :Examination
end

app/models/stu_answer.rb
class StuAnswer < ActiveRecord::Base
end

app/models/stuclass.rb
class Stuclass < ActiveRecord::Base
end

app/models/student.rb
class Student < ActiveRecord::Base
	has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_student

  def current_student
  	@current_student ||= session[:student_name] if session[:student_name]
  end

  def require_student
  	redirect_to '/login' unless current_student
  end

end

app/controllers/examinations_controller.rb
class ExaminationsController < ApplicationController

	before_action :require_student

	helper_method :exam_status, :split_choices

	def index
		@examinations = Examination.all
	end

	def add
        @examination = Examination.new
	end

	def show
		@examination = Examination.find(params[:id])
		session[:exam_id] = params[:id]
		@rand_questions_id = @examination.questions.pluck(:id).sample(3)
		@rand_questions = Question.where(id: @rand_questions_id)
	end

	def split_choices(choices)
		return choices.split("\r\n")
	end

	def create
		@examination = Examination.new(examination_params)
		if @examination.save
			redirect_to '/exam'
		else
			render 'add'
		end
	end

	def submit #交卷
		#render plain: params[:qc].inspect
		@student_id = session[:student_id]    #学生id
		@examination_id = session[:exam_id]   #考试id
		@exam_level =Examination.find(@examination_id).level

        @exam_log_new = ExamLog.new do |e|
        	e.Student_id = @student_id
        	e.Examination_id = @examination_id
        	e.exam_level = @exam_level
        	e.score = 0
        	e.save
        end

        @exam_log_id = ExamLog.last.id   #同一份考试的多次记录的id号
		@submit_answers = params[:qc]    #提交的参数
		@score = 0                       #总分初始化

        @submit_answers.each do |s|
        	@question_id = params['question_id_' + s.first]   #这里还需要过滤一下s.first
        	@student_answer = StuAnswer.new do |sa|
        		sa.Student_id = session[:student_id]
        		sa.Question_id = @question_id
        		sa.ExamLog_id = @exam_log_id
        		sa.stu_choices = s.last
        		sa.save
        	end
        	@correct_answer = Question.find(@question_id)
        	if s.last == @correct_answer.answer  #算出总分
        		@score += 1
        	end
        end

        @exam_log_update = ExamLog.find(@exam_log_id)
        @exam_log_update.update(score: @score)
	end


	def destroy
		@examination = Examination.find(params[:id])
		@examination.destroy

		redirect_to '/exam'
	end 


	def exam_status(num)
		if num==0
			return '关闭'
		elsif num==1
			return '模拟考试'
		else
			return '正式考试'
		end
	end

    private
	    def examination_params
	    	params.require(:examination).permit(:title, :exam_time, :duration, :level)
	    end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

	before_action :require_student

    def index
    	@questions = Question.all
    end

	def add
		@question = Question.new
		@examinations = Examination.all
	end

	def edit
		@question = Question.find(params[:id])
		@examinations = Examination.all
	end

	def show
	end

	def update
		@question = Question.find(params[:id])
		if @question.update(question_params)
			redirect_to '/questions'
		else
			render 'edit'
		end
	end

	#写一个helper_method , 在视图里根据id号查询考试名称

	def save
		#render plain: params[:question].inspect
		@question = Question.new(question_params)
		if @question.save
			redirect_to '/questions'
		else
			render 'add'
		end
	end

	def delete
	end

	private
		def question_params
			params.require(:question).permit(:description, :choices, :answer, :Examination_id)
		end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	def new
	end

	def create
		@student = Student.find_by_name(params[:session][:name])
		if @student && @student.authenticate(params[:session][:password])
			session[:student_id] = @student.id
			session[:student_name] = @student.name
			redirect_to '/exam'
		else
			redirect_to '/login'
		end
	end

	def destroy
		session[:student_id] = nil
		session[:student_name] = nil
		redirect_to '/login'
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/examination_helper.rb
module ExaminationHelper
end

app/helpers/examinations_helper.rb
module ExaminationsHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/examinations/add.html.erb
<h3>添加考试</h3>

<%= form_for(:examination, url: '/exam/add') do |f| %>
	<p>
		<%= f.label :title, '考试名称' %>
		<%= f.text_field :title %>
	</p>
	
	<p>
		<%= f.label :exam_time, '考试时间' %>
		<%= f.datetime_local_field :exam_time %>
	</p>
	<p>
		<%= f.label :duration, '考试时长' %>
		<%= f.text_field :duration %>		
	</p>
	
	<p>
		<%= f.label :level, '考试状态' %>
		<%= f.select(:level, [['关闭',0],['模拟考试',1],['正式考试',2]]) %>
	</p>
	
	<p>
		<%= f.submit '保存' %>	
	</p>
	
<% end %>

app/views/examinations/index.html.erb
<% content_for :css do %>
  <style type="text/css">
	  body {
	    background-color: #FFFFFF;
	  }
	  .ui.menu .item img.logo {
	    margin-right: 1.5em;
	  }
	  .main.container {
	    margin-top: 7em;
	  }
	  .wireframe {
	    margin-top: 2em;
	  }
	  .ui.footer.segment {
	    margin: 5em 0em 0em;
	    padding: 5em 0em;
	  }
  </style>
<% end %>

  <div class="ui fixed inverted menu">
    <div class="ui container">
      <div href="#" class="header item">
        <%= image_tag 'logo.png', :class=>'logo' %>
        Project Name
      </div>
      <a href="#" class="item">Home</a>
      <a href="#" class="ui simple dropdown item">
        Dropdown <i class="dropdown icon"></i>
        <div class="menu">
          <div class="item">Link Item</div>
          <div class="item">Link Item</div>
          <div class="divider"></div>
          <div class="header">Header Item</div>
          <div class="item">
            <i class="dropdown icon"></i>
            Sub Menu
            <div class="menu">
              <div class="item">Link Item</div>
              <div class="item">Link Item</div>
            </div>
          </div>
          <div class="item">Link Item</div>
        </div>
      </a>
    </div>
  </div>

 <div class="ui main text container">
    <h1 class="ui center aligned header">考试选择</h1>
    <table class="ui celled table">
		<thead>
			<th>考试名称</th>
			<th>考试时间</th>
			<th>时长</th>
			<th>状态</th>
			<th>操作</th>
		</thead>
        <% @examinations.each do |e| %>
		<tr>
			<td><%= link_to e.title, show_examination_path(e) %></td>
			<td><%= e.exam_time %></td>
			<td><%= e.duration %></td>
			<td><%= exam_status(e.level) %></td>
			<td><%= link_to '删除', delete_examination_path(e), method: 'delete', data:{confirm: '确定删除该考试？'} %></td>
		</tr>
        <% end %>
	</table>


<p>
	<%= link_to '添加考试', '/exam/add' %>
</p>

 </div>

app/views/examinations/show.html.erb
<% content_for :css do %>
  <style type="text/css">
	  .ui.card {
	    width: 100%
	  }
  </style>
<% end %>

<div class="ui text container">
	<h1 class="ui center aligned teal header"><%= @examination.title %>考试</h1>

	<%= form_tag '/exam/submit' do %>
	   <% sn=1 %>
	   <% @rand_questions.each do |q| %>

	    <%= hidden_field_tag('question_id_' + sn.to_s, q.id) %>

        <div class="ui card">
	        <div class="content">

				<div class="header">
					<%= q.id.to_s + '. ' + q.description %>
				</div>

				<div class="description">
				    <% abcd = '@' %>
					<% split_choices(q.choices).each do |s| %>
						<%= abcd.next! + '. ' + s  %><br> <!-- #下次用有序列表试试 -->
					<% end %>
				</div>

			</div>
			
			<div class="extra content">
				<div class="inline fields">
				    <%= fields_for 'qc' do |f| %>
				    	<div class="field">
					    	<div class="ui radio checkbox">
						    	<%= f.label(sn.to_s + '_a', 'A') %>
						    	<%= f.radio_button(sn, 'A') %>
					    	</div>
				    	</div>
				    	<div class="field">
					    	<div class="ui radio checkbox">
						    	<%= f.label(sn.to_s + '_b', 'B') %>
						    	<%= f.radio_button(sn, 'B') %>
					    	</div>
				    	</div>
				    	<div class="field">
					    	<div class="ui radio checkbox">
						    	<%= f.label(sn.to_s + '_c', 'C') %>
						    	<%= f.radio_button(sn, 'C') %>
					    	</div>
				    	</div>
				    	<div class="field">
					    	<div class="ui radio checkbox">
						    	<%= f.label(sn.to_s + '_d', 'D') %>
						    	<%= f.radio_button(sn, 'D') %>
					    	</div>
				    	</div>	    	
				    <% end %>
				</div>
			</div>

		</div>
		<% sn+=1 %>
	   <% end %>
	   <p class="ui center aligned header"><%= submit_tag("交卷",:class=>"ui primary button") %></p>
	<% end %>
	<script>
		$('.ui.radio.checkbox').checkbox();
	</script>
</div>

app/views/examinations/submit.html.erb
<%= @score %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>侨中考试</title>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <%= yield :css -%>
  </head>
  <body>
    <p align="right">
    	<% if current_student %>
    	<%= current_student %> 同学, 你好 | 
    	<%= link_to '注销', '/logout', method: 'delete' %>
    	<% end %>
    </p>
    <%= yield %>
  </body>
</html>

app/views/questions/add.html.erb
<h3>华侨职专在线考试 - 添加题目</h3>

<%= form_for (@question) do |f| %>
	<p>
	   <%= f.label :description, '题目描述' %><br>
	   <%= f.text_area :description, size: '60x5' %>
	</p>

	<p>
		<%= f.label :choices,'选项' %><br>
		<%= f.text_area :choices, size: '60x7' %>
	</p>

	<p>
		<%= f.label :answer, '标准答案' %><br>
		<%= f.text_field :answer %>
	</p>

	<p>
		<%= f.collection_select(:Examination_id, @examinations, :id, :title) %>
	</p>

	<p>
		<%= f.submit '添加' %>
	</p>
<% end %>

app/views/questions/edit.html.erb
<h3>华侨职专在线考试 - 编辑题目</h3>

<%= form_for @question do |f| %>
	<p>
	   <%= f.label :description, '题目描述' %><br>
	   <%= f.text_area :description, size: '60x5' %>
	</p>

	<p>
		<%= f.label :choices,'选项' %><br>
		<%= f.text_area :choices, size: '60x7' %>
	</p>

	<p>
		<%= f.label :answer, '标准答案' %><br>
		<%= f.text_field :answer %>
	</p>

	<p>
		<%= f.collection_select(:Examination_id, @examinations, :id, :title) %>
	</p>

	<p>
		<%= f.submit '保存' %>
	</p>
<% end %>

app/views/questions/index.html.erb
<h3>华侨职专在线考试</h3>

<% @questions.each do |q| %>
	<p><%= q.description %></p>
	<p><%= q.choices %></p>
	<p>[<%= link_to '编辑', edit_question_path(q) %>]</p>
	<hr>
<% end %>

<p>
	<%= link_to '添加题目', '/questions/add' %>
</p>